[build]
  # Override any UI-configured build commands since the app is pre-built locally
  command = "echo 'Deploying pre-built static files from /build/web'"
  publish = "build/web"

# Handle Flutter Web SPA routing (so refreshing doesn't cause 404s)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
