"""Add chat models

Revision ID: c720cc3ff5e2
Revises: 7db307f563e9
Create Date: 2026-09-11 02:07:56.402620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c720cc3ff5e2'
down_revision: Union[str, Sequence[str], None] = '7db307f563e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(name: str) -> bool:
    """Jadval allaqachon mavjudligini tekshiradi.

    Nima uchun kerak: `notification_broadcasts` bu loyihada avval
    (alembic'dan mustaqil ravishda, SQLAlchemy metadata.create_all
    orqali) yaratilgan edi. Shu tekshiruv bo'lmasa, bu migratsiya
    "relation already exists" xatosi bilan qulaydi.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return name in inspector.get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('chat_sessions'):
        op.create_table('chat_sessions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_resolved', sa.Boolean(), nullable=True),
        # MUHIM: users.id UUID turida. Bu yerda avval String edi va
        # "foreign key constraint cannot be implemented ... character
        # varying and uuid" xatosi bilan har bir deploy'ni qulatgan.
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('notification_broadcasts'):
        op.create_table('notification_broadcasts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('body', sa.String(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('target', sa.String(length=50), nullable=True),
        sa.Column('recipient_count', sa.Integer(), nullable=True),
        sa.Column('sent_by', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('chat_messages'):
        op.create_table('chat_messages',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('sender', sa.String(length=20), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('notification_broadcasts')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
