name: milliy_metr_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0
  dio: ^5.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.10
  file_picker: ^11.0.3
  fl_chart: ^1.2.0
  intl: ^0.20.2
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/svg/
