class RegionItem {
  final String id;
  final String nameUz;
  final String nameRu;
  final String nameEn;
  final List<DistrictItem> districts;

  const RegionItem({
    required this.id,
    required this.nameUz,
    required this.nameRu,
    required this.nameEn,
    required this.districts,
  });

  String getName(String langCode) {
    if (langCode == 'ru') return nameRu;
    if (langCode == 'en') return nameEn;
    return nameUz;
  }
}

class DistrictItem {
  final String id;
  final String nameUz;
  final String nameRu;
  final String nameEn;

  const DistrictItem({
    required this.id,
    required this.nameUz,
    required this.nameRu,
    required this.nameEn,
  });

  String getName(String langCode) {
    if (langCode == 'ru') return nameRu;
    if (langCode == 'en') return nameEn;
    return nameUz;
  }
}

const List<RegionItem> uzbekistanRegionsData = [
  RegionItem(
    id: 'samarkand',
    nameUz: 'Samarqand viloyati',
    nameRu: 'Самаркандская область',
    nameEn: 'Samarkand Region',
    districts: [
      DistrictItem(id: 'jomboy', nameUz: 'Jomboy tumani', nameRu: 'Джамбайский район', nameEn: 'Jomboy District'),
      DistrictItem(id: 'samarkand_city', nameUz: 'Samarqand shahri', nameRu: 'город Самарканд', nameEn: 'Samarkand City'),
      DistrictItem(id: 'urgut', nameUz: 'Urgut tumani', nameRu: 'Ургутский район', nameEn: 'Urgut District'),
      DistrictItem(id: 'pastdargom', nameUz: 'Pastdarg\'om tumani', nameRu: 'Пастдаргомский район', nameEn: 'Pastdargom District'),
      DistrictItem(id: 'bulungur', nameUz: 'Bulung\'ur tumani', nameRu: 'Булунгурский район', nameEn: 'Bulungur District'),
      DistrictItem(id: 'toyloq', nameUz: 'Toyloq tumani', nameRu: 'Тайлякский район', nameEn: 'Toyloq District'),
      DistrictItem(id: 'ishtixon', nameUz: 'Ishtixon tumani', nameRu: 'Иштыханский район', nameEn: 'Ishtixon District'),
      DistrictItem(id: 'kattaqorgon_city', nameUz: 'Kattaqo\'rg\'on shahri', nameRu: 'город Каттакурган', nameEn: 'Kattaqorgon City'),
      DistrictItem(id: 'kattaqorgon_t', nameUz: 'Kattaqo\'rg\'on tumani', nameRu: 'Каттакурганский район', nameEn: 'Kattaqorgon District'),
      DistrictItem(id: 'narpay', nameUz: 'Narpay tumani', nameRu: 'Нарпайский район', nameEn: 'Narpay District'),
      DistrictItem(id: 'oqdaryo', nameUz: 'Oqdaryo tumani', nameRu: 'Акдарьинский район', nameEn: 'Oqdaryo District'),
      DistrictItem(id: 'paxtachi', nameUz: 'Paxtachi tumani', nameRu: 'Пахтачийский район', nameEn: 'Paxtachi District'),
      DistrictItem(id: 'payariq', nameUz: 'Payariq tumani', nameRu: 'Паярыкский район', nameEn: 'Payariq District'),
      DistrictItem(id: 'qoshrabot', nameUz: 'Qo\'shrabot tumani', nameRu: 'Кошрабадский район', nameEn: 'Qoshrabot District'),
    ],
  ),
  RegionItem(
    id: 'tashkent_city',
    nameUz: 'Toshkent shahri',
    nameRu: 'город Ташкент',
    nameEn: 'Tashkent City',
    districts: [
      DistrictItem(id: 'yunusobod', nameUz: 'Yunusobod tumani', nameRu: 'Юнусабадский район', nameEn: 'Yunusabad District'),
      DistrictItem(id: 'chilonzor', nameUz: 'Chilonzor tumani', nameRu: 'Чиланзарский район', nameEn: 'Chilanzar District'),
      DistrictItem(id: 'mirzo_ulugbek', nameUz: 'Mirzo Ulug\'bek tumani', nameRu: 'Мирзо-Улугбекский район', nameEn: 'Mirzo Ulugbek District'),
      DistrictItem(id: 'yakkasaroy', nameUz: 'Yakkasaroy tumani', nameRu: 'Яккасарайский район', nameEn: 'Yakkasaray District'),
      DistrictItem(id: 'yashnobod', nameUz: 'Yashnobod tumani', nameRu: 'Яшнабадский район', nameEn: 'Yashnabad District'),
      DistrictItem(id: 'shayxontohur', nameUz: 'Shayxontohur tumani', nameRu: 'Шайхантахурский район', nameEn: 'Shaykhontokhur District'),
      DistrictItem(id: 'olmazor', nameUz: 'Olmazor tumani', nameRu: 'Алмазарский район', nameEn: 'Olmazor District'),
      DistrictItem(id: 'uchtepa', nameUz: 'Uchtepa tumani', nameRu: 'Учтепинский район', nameEn: 'Uchtepa District'),
      DistrictItem(id: 'mirobod', nameUz: 'Mirobod tumani', nameRu: 'Мирабадский район', nameEn: 'Mirobod District'),
      DistrictItem(id: 'sergeli', nameUz: 'Sergeli tumani', nameRu: 'Сергелийский район', nameEn: 'Sergeli District'),
      DistrictItem(id: 'yangihayot', nameUz: 'Yangihayot tumani', nameRu: 'Янгихаётский район', nameEn: 'Yangihayot District'),
      DistrictItem(id: 'bektemir', nameUz: 'Bektemir tumani', nameRu: 'Бектемирский район', nameEn: 'Bektemir District'),
    ],
  ),
  RegionItem(
    id: 'tashkent_region',
    nameUz: 'Toshkent viloyati',
    nameRu: 'Ташкентская область',
    nameEn: 'Tashkent Region',
    districts: [
      DistrictItem(id: 'nurafshon', nameUz: 'Nurafshon shahri', nameRu: 'город Нурафшан', nameEn: 'Nurafshon City'),
      DistrictItem(id: 'chirchiq', nameUz: 'Chirchiq shahri', nameRu: 'город Чирчик', nameEn: 'Chirchiq City'),
      DistrictItem(id: 'olmaliq', nameUz: 'Olmaliq shahri', nameRu: 'город Алмалык', nameEn: 'Olmaliq City'),
      DistrictItem(id: 'angren', nameUz: 'Angren shahri', nameRu: 'город Ангрен', nameEn: 'Angren City'),
      DistrictItem(id: 'bekobod_sh', nameUz: 'Bekobod shahri', nameRu: 'город Бекабад', nameEn: 'Bekobod City'),
      DistrictItem(id: 'yangiyol_sh', nameUz: 'Yangiyo\'l shahri', nameRu: 'город Янгиюль', nameEn: 'Yangiyol City'),
      DistrictItem(id: 'bostonliq', nameUz: 'Bo\'stonliq tumani', nameRu: 'Бостанлыкский район', nameEn: 'Bostonliq District'),
      DistrictItem(id: 'zangiota', nameUz: 'Zangiota tumani', nameRu: 'Зангиатинский район', nameEn: 'Zangiota District'),
      DistrictItem(id: 'qibray', nameUz: 'Qibray tumani', nameRu: 'Кибрайский район', nameEn: 'Qibray District'),
      DistrictItem(id: 'toshkent_t', nameUz: 'Toshkent tumani', nameRu: 'Ташкентский район', nameEn: 'Tashkent District'),
      DistrictItem(id: 'parkent', nameUz: 'Parkent tumani', nameRu: 'Паркентский район', nameEn: 'Parkent District'),
      DistrictItem(id: 'piskent', nameUz: 'Piskent tumani', nameRu: 'Пскентский район', nameEn: 'Piskent District'),
      DistrictItem(id: 'ortachirchiq', nameUz: 'O\'rtachirchiq tumani', nameRu: 'Уртачирчикский район', nameEn: 'Ortachirchiq District'),
      DistrictItem(id: 'quyichirchiq', nameUz: 'Quyichirchiq tumani', nameRu: 'Куйичирчикский район', nameEn: 'Quyichirchiq District'),
      DistrictItem(id: 'oqqorgon', nameUz: 'Oqqo\'rg\'on tumani', nameRu: 'Аккурганский район', nameEn: 'Oqqorgon District'),
      DistrictItem(id: 'boka', nameUz: 'Bo\'ka tumani', nameRu: 'Букинский район', nameEn: 'Boka District'),
      DistrictItem(id: 'chinoz', nameUz: 'Chinoz tumani', nameRu: 'Чиназский район', nameEn: 'Chinoz District'),
      DistrictItem(id: 'yuqorichirchiq', nameUz: 'Yuqorichirchiq tumani', nameRu: 'Юкоричирчикский район', nameEn: 'Yuqorichirchiq District'),
    ],
  ),
  RegionItem(
    id: 'andijan',
    nameUz: 'Andijon viloyati',
    nameRu: 'Андижанская область',
    nameEn: 'Andijan Region',
    districts: [
      DistrictItem(id: 'andijan_city', nameUz: 'Andijon shahri', nameRu: 'город Андижан', nameEn: 'Andijan City'),
      DistrictItem(id: 'xonobod', nameUz: 'Xonobod shahri', nameRu: 'город Ханабад', nameEn: 'Xonobod City'),
      DistrictItem(id: 'andijan_t', nameUz: 'Andijon tumani', nameRu: 'Андижанский район', nameEn: 'Andijan District'),
      DistrictItem(id: 'asaka', nameUz: 'Asaka tumani', nameRu: 'Асакинский район', nameEn: 'Asaka District'),
      DistrictItem(id: 'baliqchi', nameUz: 'Baliqchi tumani', nameRu: 'Балыкчинский район', nameEn: 'Baliqchi District'),
      DistrictItem(id: 'boz', nameUz: 'Bo\'z tumani', nameRu: 'Бозский район', nameEn: 'Boz District'),
      DistrictItem(id: 'buloqboshi', nameUz: 'Buloqboshi tumani', nameRu: 'Булакбашинский район', nameEn: 'Buloqboshi District'),
      DistrictItem(id: 'izboskan', nameUz: 'Izboskan tumani', nameRu: 'Избасканский район', nameEn: 'Izboskan District'),
      DistrictItem(id: 'jalaquduq', nameUz: 'Jalaquduq tumani', nameRu: 'Джалакудукский район', nameEn: 'Jalaquduq District'),
      DistrictItem(id: 'marhamat', nameUz: 'Marhamat tumani', nameRu: 'Мархаматский район', nameEn: 'Marhamat District'),
      DistrictItem(id: 'oltinkol', nameUz: 'Oltinko\'l tumani', nameRu: 'Алтынкульский район', nameEn: 'Oltinkol District'),
      DistrictItem(id: 'paxtaobod', nameUz: 'Paxtaobod tumani', nameRu: 'Пахтаабадский район', nameEn: 'Paxtaobod District'),
      DistrictItem(id: 'shahrixon', nameUz: 'Шахриханский район', nameRu: 'Шахриханский район', nameEn: 'Shahrixon District'),
      DistrictItem(id: 'ulugnor', nameUz: 'Ulug\'nor tumani', nameRu: 'Улугнорский район', nameEn: 'Ulugnor District'),
      DistrictItem(id: 'xojaobod', nameUz: 'Xo\'jaobod tumani', nameRu: 'Ходжаабадский район', nameEn: 'Xojaobod District'),
      DistrictItem(id: 'qorgontepa', nameUz: 'Qo\'rg\'ontepa tumani', nameRu: 'Кургантепинский район', nameEn: 'Qorgontepa District'),
    ],
  ),
  RegionItem(
    id: 'fergana',
    nameUz: 'Farg\'ona viloyati',
    nameRu: 'Ферганская область',
    nameEn: 'Fergana Region',
    districts: [
      DistrictItem(id: 'fergana_city', nameUz: 'Farg\'ona shahri', nameRu: 'город Фергана', nameEn: 'Fergana City'),
      DistrictItem(id: 'margilon', nameUz: 'Marg\'ilon shahri', nameRu: 'город Маргилан', nameEn: 'Margilon City'),
      DistrictItem(id: 'qoqon', nameUz: 'Qo\'qon shahri', nameRu: 'город Коканд', nameEn: 'Qoqon City'),
      DistrictItem(id: 'quvasoy', nameUz: 'Quvasoy shahri', nameRu: 'город Кувасай', nameEn: 'Quvasoy City'),
      DistrictItem(id: 'oltiariq', nameUz: 'Oltiariq tumani', nameRu: 'Алтыарыкский район', nameEn: 'Oltiariq District'),
      DistrictItem(id: 'bogdod', nameUz: 'Bog\'dod tumani', nameRu: 'Багдадский район', nameEn: 'Bogdod District'),
      DistrictItem(id: 'beshariq', nameUz: 'Beshariq tumani', nameRu: 'Бешарыкский район', nameEn: 'Beshariq District'),
      DistrictItem(id: 'buvayda', nameUz: 'Buvayda tumani', nameRu: 'Бувайдинский район', nameEn: 'Buvayda District'),
      DistrictItem(id: 'dangara', nameUz: 'Dang\'ara tumani', nameRu: 'Дангаринский район', nameEn: 'Dangara District'),
      DistrictItem(id: 'fergana_t', nameUz: 'Farg\'ona tumani', nameRu: 'Ферганский район', nameEn: 'Fergana District'),
      DistrictItem(id: 'furqat', nameUz: 'Furqat tumani', nameRu: 'Фуркатский район', nameEn: 'Furqat District'),
      DistrictItem(id: 'qushtepa', nameUz: 'Qushtepa tumani', nameRu: 'Куштепинский район', nameEn: 'Qushtepa District'),
      DistrictItem(id: 'rishton', nameUz: 'Rishton tumani', nameRu: 'Риштанский район', nameEn: 'Rishton District'),
      DistrictItem(id: 'sox', nameUz: 'So\'x tumani', nameRu: 'Сохский район', nameEn: 'Sox District'),
      DistrictItem(id: 'toshloq', nameUz: 'Toshloq tumani', nameRu: 'Ташлакский район', nameEn: 'Toshloq District'),
      DistrictItem(id: 'ozbekiston_t', nameUz: 'O\'zbekiston tumani', nameRu: 'Узбекистанский район', nameEn: 'Ozbekiston District'),
      DistrictItem(id: 'uchkoprik', nameUz: 'Uchko\'prik tumani', nameRu: 'Учкуприкский район', nameEn: 'Uchkoprik District'),
      DistrictItem(id: 'yozyovon', nameUz: 'Yozyovon tumani', nameRu: 'Язъяванский район', nameEn: 'Yozyovon District'),
    ],
  ),
  RegionItem(
    id: 'namangan',
    nameUz: 'Namangan viloyati',
    nameRu: 'Наманганская область',
    nameEn: 'Namangan Region',
    districts: [
      DistrictItem(id: 'namangan_city', nameUz: 'Namangan shahri', nameRu: 'город Наманган', nameEn: 'Namangan City'),
      DistrictItem(id: 'chortoq', nameUz: 'Chortoq tumani', nameRu: 'Чартакский район', nameEn: 'Chortoq District'),
      DistrictItem(id: 'chust', nameUz: 'Chust tumani', nameRu: 'Чустский район', nameEn: 'Chust District'),
      DistrictItem(id: 'kosonsoy', nameUz: 'Kosonsoy tumani', nameRu: 'Касансайский район', nameEn: 'Kosonsoy District'),
      DistrictItem(id: 'mingbuloq', nameUz: 'Mingbuloq tumani', nameRu: 'Мингбулакский район', nameEn: 'Mingbuloq District'),
      DistrictItem(id: 'namangan_t', nameUz: 'Namangan tumani', nameRu: 'Наманганский район', nameEn: 'Namangan District'),
      DistrictItem(id: 'norin', nameUz: 'Norin tumani', nameRu: 'Нарынский район', nameEn: 'Norin District'),
      DistrictItem(id: 'pop', nameUz: 'Pop tumani', nameRu: 'Папский район', nameEn: 'Pop District'),
      DistrictItem(id: 'toraqorgon', nameUz: 'To\'raqo\'rg\'on tumani', nameRu: 'Туракурганский район', nameEn: 'Toraqorgon District'),
      DistrictItem(id: 'uychi', nameUz: 'Uychi tumani', nameRu: 'Уйчинский район', nameEn: 'Uychi District'),
      DistrictItem(id: 'yangiqorgon', nameUz: 'Yangiqo\'rg\'on tumani', nameRu: 'Янгикурганский район', nameEn: 'Yangiqorgon District'),
      DistrictItem(id: 'uchqorgon', nameUz: 'Uchqo\'rg\'on tumani', nameRu: 'Учкурганский район', nameEn: 'Uchqorgon District'),
    ],
  ),
  RegionItem(
    id: 'bukhara',
    nameUz: 'Buxoro viloyati',
    nameRu: 'Бухарская область',
    nameEn: 'Bukhara Region',
    districts: [
      DistrictItem(id: 'bukhara_city', nameUz: 'Buxoro shahri', nameRu: 'город Бухара', nameEn: 'Bukhara City'),
      DistrictItem(id: 'kogon_city', nameUz: 'Kogon shahri', nameRu: 'город Каган', nameEn: 'Kogon City'),
      DistrictItem(id: 'bukhara_t', nameUz: 'Buxoro tumani', nameRu: 'Бухарский район', nameEn: 'Bukhara District'),
      DistrictItem(id: 'vobkent', nameUz: 'Vobkent tumani', nameRu: 'Вабкентский район', nameEn: 'Vobkent District'),
      DistrictItem(id: 'jondor', nameUz: 'Jondor tumani', nameRu: 'Жондорский район', nameEn: 'Jondor District'),
      DistrictItem(id: 'kogon_t', nameUz: 'Kogon tumani', nameRu: 'Каганский район', nameEn: 'Kogon District'),
      DistrictItem(id: 'qorakol', nameUz: 'Qorako\'l tumani', nameRu: 'Каракульский район', nameEn: 'Qorakol District'),
      DistrictItem(id: 'qorovulbozor', nameUz: 'Qorovulbozor tumani', nameRu: 'Караулбазарский район', nameEn: 'Qorovulbozor District'),
      DistrictItem(id: 'peshku', nameUz: 'Peshku tumani', nameRu: 'Пешкунский район', nameEn: 'Peshku District'),
      DistrictItem(id: 'romitan', nameUz: 'Romitan tumani', nameRu: 'Ромитанский район', nameEn: 'Romitan District'),
      DistrictItem(id: 'shofirkon', nameUz: 'Shofirkon tumani', nameRu: 'Шафирканский район', nameEn: 'Shofirkon District'),
      DistrictItem(id: 'gijduvon', nameUz: 'G\'ijduvon tumani', nameRu: 'Гиждуванский район', nameEn: 'Gijduvon District'),
      DistrictItem(id: 'olot', nameUz: 'Olot tumani', nameRu: 'Алатский район', nameEn: 'Olot District'),
    ],
  ),
  RegionItem(
    id: 'khorezm',
    nameUz: 'Xorazm viloyati',
    nameRu: 'Хорезмская область',
    nameEn: 'Khorezm Region',
    districts: [
      DistrictItem(id: 'urganch_city', nameUz: 'Urganch shahri', nameRu: 'город Ургенч', nameEn: 'Urganch City'),
      DistrictItem(id: 'xiva_city', nameUz: 'Xiva shahri', nameRu: 'город Хива', nameEn: 'Xiva City'),
      DistrictItem(id: 'bogot', nameUz: 'Bog\'ot tumani', nameRu: 'Багатский район', nameEn: 'Bogot District'),
      DistrictItem(id: 'gurlan', nameUz: 'Gurlan tumani', nameRu: 'Гурленский район', nameEn: 'Gurlan District'),
      DistrictItem(id: 'qoshkopir', nameUz: 'Qo\'shko\'pir tumani', nameRu: 'Кошкупырский район', nameEn: 'Qoshkopir District'),
      DistrictItem(id: 'urganch_t', nameUz: 'Urganch tumani', nameRu: 'Ургенчский район', nameEn: 'Urganch District'),
      DistrictItem(id: 'hazorasp', nameUz: 'Hazorasp tumani', nameRu: 'Хазараспский район', nameEn: 'Hazorasp District'),
      DistrictItem(id: 'xonqa', nameUz: 'Xonqa tumani', nameRu: 'Ханкинский район', nameEn: 'Xonqa District'),
      DistrictItem(id: 'xiva_t', nameUz: 'Xiva tumani', nameRu: 'Хивинский район', nameEn: 'Xiva District'),
      DistrictItem(id: 'shovot', nameUz: 'Shovot tumani', nameRu: 'Шаватский район', nameEn: 'Shovot District'),
      DistrictItem(id: 'yangiariq', nameUz: 'Yangiariq tumani', nameRu: 'Янгиарыкский район', nameEn: 'Yangiariq District'),
      DistrictItem(id: 'yangibozor', nameUz: 'Yangibozor tumani', nameRu: 'Янгибазарский район', nameEn: 'Yangibozor District'),
      DistrictItem(id: 'tuproqqala', nameUz: 'Tuproqqal\'a tumani', nameRu: 'Тупраккалинский район', nameEn: 'Tuproqqala District'),
    ],
  ),
  RegionItem(
    id: 'kashkadarya',
    nameUz: 'Qashqadaryo viloyati',
    nameRu: 'Кашкадарьинская область',
    nameEn: 'Kashkadarya Region',
    districts: [
      DistrictItem(id: 'qarshi_city', nameUz: 'Qarshi shahri', nameRu: 'город Карши', nameEn: 'Qarshi City'),
      DistrictItem(id: 'shahrisabz_city', nameUz: 'Shahrisabz shahri', nameRu: 'город Шахрисабз', nameEn: 'Shahrisabz City'),
      DistrictItem(id: 'dehqonobod', nameUz: 'Dehqonobod tumani', nameRu: 'Дехканабадский район', nameEn: 'Dehqonobod District'),
      DistrictItem(id: 'kasbi', nameUz: 'Kasbi tumani', nameRu: 'Касбийский район', nameEn: 'Kasbi District'),
      DistrictItem(id: 'kitob', nameUz: 'Kitob tumani', nameRu: 'Китабский район', nameEn: 'Kitob District'),
      DistrictItem(id: 'koson', nameUz: 'Koson tumani', nameRu: 'Касанский район', nameEn: 'Koson District'),
      DistrictItem(id: 'mirishkor', nameUz: 'Mirishkor tumani', nameRu: 'Миришкорский район', nameEn: 'Mirishkor District'),
      DistrictItem(id: 'muborak', nameUz: 'Muborak tumani', nameRu: 'Мубарекский район', nameEn: 'Muborak District'),
      DistrictItem(id: 'nishon', nameUz: 'Nishon tumani', nameRu: 'Нишанский район', nameEn: 'Nishon District'),
      DistrictItem(id: 'qamashi', nameUz: 'Qamashi tumani', nameRu: 'Камашинский район', nameEn: 'Qamashi District'),
      DistrictItem(id: 'qarshi_t', nameUz: 'Qarshi tumani', nameRu: 'Каршинский район', nameEn: 'Qarshi District'),
      DistrictItem(id: 'chiroqchi', nameUz: 'Chiroqchi tumani', nameRu: 'Чиракчинский район', nameEn: 'Chiroqchi District'),
      DistrictItem(id: 'shahrisabz_t', nameUz: 'Shahrisabz tumani', nameRu: 'Шахрисабзский район', nameEn: 'Shahrisabz District'),
      DistrictItem(id: 'yakkabog', nameUz: 'Yakkabog\' tumani', nameRu: 'Яккабагский район', nameEn: 'Yakkabog District'),
      DistrictItem(id: 'kokdala', nameUz: 'Ko\'kdala tumani', nameRu: 'Кукдалинский район', nameEn: 'Kokdala District'),
    ],
  ),
  RegionItem(
    id: 'surkhandarya',
    nameUz: 'Surxondaryo viloyati',
    nameRu: 'Сурхандарьинская область',
    nameEn: 'Surkhandarya Region',
    districts: [
      DistrictItem(id: 'termiz_city', nameUz: 'Termiz shahri', nameRu: 'город Термез', nameEn: 'Termiz City'),
      DistrictItem(id: 'angor', nameUz: 'Angor tumani', nameRu: 'Ангорский район', nameEn: 'Angor District'),
      DistrictItem(id: 'bandixon', nameUz: 'Bandixon tumani', nameRu: 'Бандиханский район', nameEn: 'Bandixon District'),
      DistrictItem(id: 'boysun', nameUz: 'Boysun tumani', nameRu: 'Байсунский район', nameEn: 'Boysun District'),
      DistrictItem(id: 'denov', nameUz: 'Denov tumani', nameRu: 'Денауский район', nameEn: 'Denov District'),
      DistrictItem(id: 'jarqorgon', nameUz: 'Jarqo\'rg\'on tumani', nameRu: 'Джаркурганский район', nameEn: 'Jarqorgon District'),
      DistrictItem(id: 'muzrabot', nameUz: 'Muzrabot tumani', nameRu: 'Музрабадский район', nameEn: 'Muzrabot District'),
      DistrictItem(id: 'oltinsoy', nameUz: 'Oltinsoy tumani', nameRu: 'Алтынсайский район', nameEn: 'Oltinsoy District'),
      DistrictItem(id: 'qiziriq', nameUz: 'Qiziriq tumani', nameRu: 'Кизирикский район', nameEn: 'Qiziriq District'),
      DistrictItem(id: 'qumqorgon', nameUz: 'Qumqo\'rg\'on tumani', nameRu: 'Кумкурганский район', nameEn: 'Qumqorgon District'),
      DistrictItem(id: 'sariosiyo', nameUz: 'Sariosiyo tumani', nameRu: 'Сариасийский район', nameEn: 'Sariosiyo District'),
      DistrictItem(id: 'sherobod', nameUz: 'Sherobod tumani', nameRu: 'Шерабадский район', nameEn: 'Sherobod District'),
      DistrictItem(id: 'shorchi', nameUz: 'Sho\'rchi tumani', nameRu: 'Шурчинский район', nameEn: 'Shorchi District'),
      DistrictItem(id: 'termiz_t', nameUz: 'Termiz tumani', nameRu: 'Термезский район', nameEn: 'Termiz District'),
      DistrictItem(id: 'uzun', nameUz: 'Uzun tumani', nameRu: 'Узунский район', nameEn: 'Uzun District'),
    ],
  ),
  RegionItem(
    id: 'navoiy',
    nameUz: 'Navoiy viloyati',
    nameRu: 'Навоийская область',
    nameEn: 'Navoiy Region',
    districts: [
      DistrictItem(id: 'navoiy_city', nameUz: 'Navoiy shahri', nameRu: 'город Навои', nameEn: 'Navoiy City'),
      DistrictItem(id: 'zarafshon', nameUz: 'Zarafshon shahri', nameRu: 'город Зарафшан', nameEn: 'Zarafshon City'),
      DistrictItem(id: 'karmana', nameUz: 'Karmana tumani', nameRu: 'Карманинский район', nameEn: 'Karmana District'),
      DistrictItem(id: 'konimex', nameUz: 'Konimex tumani', nameRu: 'Канимехский район', nameEn: 'Konimex District'),
      DistrictItem(id: 'qiziltepa', nameUz: 'Qiziltepa tumani', nameRu: 'Кызылтепинский район', nameEn: 'Qiziltepa District'),
      DistrictItem(id: 'xatirchi', nameUz: 'Xatirchi tumani', nameRu: 'Хатырчинский район', nameEn: 'Xatirchi District'),
      DistrictItem(id: 'navbahor', nameUz: 'Navbahor tumani', nameRu: 'Навбахорский район', nameEn: 'Navbahor District'),
      DistrictItem(id: 'nurota', nameUz: 'Nurota tumani', nameRu: 'Нуратинский район', nameEn: 'Nurota District'),
      DistrictItem(id: 'tomdi', nameUz: 'Tomdi tumani', nameRu: 'Тамдынский район', nameEn: 'Tomdi District'),
      DistrictItem(id: 'uchquduq', nameUz: 'Uchquduq tumani', nameRu: 'Учкудукский район', nameEn: 'Uchquduq District'),
    ],
  ),
  RegionItem(
    id: 'jizzakh',
    nameUz: 'Jizzax viloyati',
    nameRu: 'Джизакская область',
    nameEn: 'Jizzakh Region',
    districts: [
      DistrictItem(id: 'jizzakh_city', nameUz: 'Jizzax shahri', nameRu: 'город Джизак', nameEn: 'Jizzakh City'),
      DistrictItem(id: 'arnasoy', nameUz: 'Arnasoy tumani', nameRu: 'Арнасайский район', nameEn: 'Arnasoy District'),
      DistrictItem(id: 'baxmal', nameUz: 'Baxmal tumani', nameRu: 'Бахмальский район', nameEn: 'Baxmal District'),
      DistrictItem(id: 'dostlik', nameUz: 'Do\'stlik tumani', nameRu: 'Дустликский район', nameEn: 'Dostlik District'),
      DistrictItem(id: 'forish', nameUz: 'Forish tumani', nameRu: 'Фаришский район', nameEn: 'Forish District'),
      DistrictItem(id: 'gallaorol', nameUz: 'G\'allaorol tumani', nameRu: 'Галляаральский район', nameEn: 'Gallaorol District'),
      DistrictItem(id: 'sharof_rashidov', nameUz: 'Sharof Rashidov tumani', nameRu: 'Шараф-Рашидовский район', nameEn: 'Sharof Rashidov District'),
      DistrictItem(id: 'mirzachol', nameUz: 'Mirzacho\'l tumani', nameRu: 'Мирзачульский район', nameEn: 'Mirzachol District'),
      DistrictItem(id: 'paxtakor', nameUz: 'Paxtakor tumani', nameRu: 'Пахтакорский район', nameEn: 'Paxtakor District'),
      DistrictItem(id: 'yangiobod', nameUz: 'Yangiobod tumani', nameRu: 'Янгиабадский район', nameEn: 'Yangiobod District'),
      DistrictItem(id: 'zomin', nameUz: 'Zomin tumani', nameRu: 'Зааминский район', nameEn: 'Zomin District'),
      DistrictItem(id: 'zafarobod', nameUz: 'Zafarobod tumani', nameRu: 'Зафарабадский район', nameEn: 'Zafarobod District'),
      DistrictItem(id: 'zarbdor', nameUz: 'Zarbdor tumani', nameRu: 'Зарбдарский район', nameEn: 'Zarbdor District'),
    ],
  ),
  RegionItem(
    id: 'sirdaryo',
    nameUz: 'Sirdaryo viloyati',
    nameRu: 'Сырдарьинская область',
    nameEn: 'Sirdaryo Region',
    districts: [
      DistrictItem(id: 'guliston_city', nameUz: 'Guliston shahri', nameRu: 'город Гулистан', nameEn: 'Guliston City'),
      DistrictItem(id: 'shirin', nameUz: 'Shirin shahri', nameRu: 'город Ширин', nameEn: 'Shirin City'),
      DistrictItem(id: 'yangiyer', nameUz: 'Yangiyer shahri', nameRu: 'город Янгиер', nameEn: 'Yangiyer City'),
      DistrictItem(id: 'boyovut', nameUz: 'Boyovut tumani', nameRu: 'Баяутский район', nameEn: 'Boyovut District'),
      DistrictItem(id: 'guliston_t', nameUz: 'Guliston tumani', nameRu: 'Гулистанский район', nameEn: 'Guliston District'),
      DistrictItem(id: 'mirzaobod', nameUz: 'Мирзаабадский район', nameRu: 'Мирзаабадский район', nameEn: 'Mirzaobod District'),
      DistrictItem(id: 'oqoltin', nameUz: 'Oqoltin tumani', nameRu: 'Акалтынский район', nameEn: 'Oqoltin District'),
      DistrictItem(id: 'sardoba', nameUz: 'Sardoba tumani', nameRu: 'Сардобинский район', nameEn: 'Sardoba District'),
      DistrictItem(id: 'sayxunobod', nameUz: 'Sayxunobod tumani', nameRu: 'Сайхунабадский район', nameEn: 'Sayxunobod District'),
      DistrictItem(id: 'sirdaryo_t', nameUz: 'Sirdaryo tumani', nameRu: 'Сырдарьинский район', nameEn: 'Sirdaryo District'),
      DistrictItem(id: 'xovos', nameUz: 'Xovos tumani', nameRu: 'Хавастский район', nameEn: 'Xovos District'),
    ],
  ),
  RegionItem(
    id: 'karakalpakstan',
    nameUz: 'Qoraqalpog\'iston Respublikasi',
    nameRu: 'Республика Каракалпакстан',
    nameEn: 'Republic of Karakalpakstan',
    districts: [
      DistrictItem(id: 'nukus_city', nameUz: 'Nukus shahri', nameRu: 'город Нукус', nameEn: 'Nukus City'),
      DistrictItem(id: 'amudaryo', nameUz: 'Amudaryo tumani', nameRu: 'Амударьинский район', nameEn: 'Amudaryo District'),
      DistrictItem(id: 'beruniy', nameUz: 'Beruniy tumani', nameRu: 'Берунийский район', nameEn: 'Beruniy District'),
      DistrictItem(id: 'qoraozak', nameUz: 'Qorao\'zak tumani', nameRu: 'Караузякский район', nameEn: 'Qoraozak District'),
      DistrictItem(id: 'kegeyli', nameUz: 'Kegeyli tumani', nameRu: 'Кегейлийский район', nameEn: 'Kegeyli District'),
      DistrictItem(id: 'qongirot', nameUz: 'Qo\'ng\'irot tumani', nameRu: 'Кунградский район', nameEn: 'Qongirot District'),
      DistrictItem(id: 'qanlikol', nameUz: 'Qanliko\'l tumani', nameRu: 'Канлыкульский район', nameEn: 'Qanlikol District'),
      DistrictItem(id: 'moynoq', nameUz: 'Mo\'ynoq tumani', nameRu: 'Муйнакский район', nameEn: 'Moynoq District'),
      DistrictItem(id: 'nukus_t', nameUz: 'Nukus tumani', nameRu: 'Нукусский район', nameEn: 'Nukus District'),
      DistrictItem(id: 'taxiatosh', nameUz: 'Taxiatosh tumani', nameRu: 'Тахиаташский район', nameEn: 'Taxiatosh District'),
      DistrictItem(id: 'taxtakopir', nameUz: 'Taxtako\'pir tumani', nameRu: 'Тахтакупырский район', nameEn: 'Taxtakopir District'),
      DistrictItem(id: 'tortkol', nameUz: 'To\'rtko\'l tumani', nameRu: 'Турткульский район', nameEn: 'Tortkol District'),
      DistrictItem(id: 'xojayli', nameUz: 'Xo\'jayli tumani', nameRu: 'Ходжейлийский район', nameEn: 'Xojayli District'),
      DistrictItem(id: 'chimboy', nameUz: 'Chimboy tumani', nameRu: 'Чимбайский район', nameEn: 'Chimboy District'),
      DistrictItem(id: 'shomanoy', nameUz: 'Sho\'manoy tumani', nameRu: 'Шуманайский район', nameEn: 'Shomanoy District'),
      DistrictItem(id: 'ellikqala', nameUz: 'Ellikqala tumani', nameRu: 'Элликкалинский район', nameEn: 'Ellikqala District'),
    ],
  ),
];
